### ISSUE TITLE
How Can I run this?

### ISSUE THREAD

**Issue by justingolden21** [gamescomputersplay/minesweeper-solver#11]
Downloaded and ran Minesweeper X, cloned the repo, and installed dependencies and tried running both minesweeper_game and minesweeper_bot but nothing happened. Output:

```cmd
C:\Users\User\Documents\GitHub\minesweeper-solver> cmd /C "C:\Users\User\AppData\Local\Microsoft\WindowsApps\python3.10.exe c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 52175 -- c:\Users\User\Documents\GitHub\minesweeper-solver\minesweeper_game.py "
Move: 
C:\Users\User\Documents\GitHub\minesweeper-solver> c: && cd c:\Users\User\Documents\GitHub\minesweeper-solver && 
cmd /C "C:\Users\User\AppData\Local\Microsoft\WindowsApps\python3.10.exe c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 52185 -- c:\Users\User\Documents\GitHub\minesweeper-solver\minesweeper_bot.py "

C:\Users\User\Documents\GitHub\minesweeper-solver>
```

**Comment by justingolden21** [comment]
I think adding some instructions to run to README and a requirements file for pip would be super helpful : )

**Comment by gamescomputersplay** [comment]
hi there

I have added this to the Reame file:

To run the bot:
1. Clone the repo, have all the dependencies installed.
2. Launch minesweeper_bot.py
3. Bring the minesweeper game to the screen (it should display unclicked empty field).
4. Press F10. The bot should find the game on the screen and play 10 games.

That shoudl do it. Let me know if if worked for you.

**Comment by justingolden21** [comment]
Awesome, it works! Thanks. 

Notably, the program halts when it gets a new fastest time:

![image](https://user-images.githubusercontent.com/30274440/208573554-b9cde71d-23e6-4ca3-9525-5a256a770cd6.png)

```
I won. Win rate: 80.00%
Game #6. Some cells were not recognized, but  STOP_AT_UNKNOWN_CELL is set 
to False.
I won. Win rate: 83.33%
Game #7. Some cells were not recognized, but  STOP_AT_UNKNOWN_CELL is set 
to False.
I won. Win rate: 85.71%
Game #8. Some cells were not recognized, but  STOP_AT_UNKNOWN_CELL is set 
to False.
I won. Win rate: 87.50%
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code       
    exec(code, run_globals)
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main     
    run()
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file 
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\User\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\User\Documents\GitHub\minesweeper-solver\minesweeper_bot.py", line 640, in <module>
    keyboard.wait('esc')
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keyboard\__init__.py", line 882, in wait
    lock.wait()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keyboard\__init__.py", line 117, in wait
    if _UninterruptibleEvent.wait(self, 0.5):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 607, in wait       
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 324, in wait       
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
Game #9. Some cells were not recognized, but  STOP_AT_UNKNOWN_CELL is set 
to False.
```

But don't feel obligated to work on that lol. I'm probably the only one staring at this code. Was mostly drawing inspiration for my own solver, but all the code online is hard to read through lol.

**Comment by gamescomputersplay** [comment]
Cool, The  current logic is, if the cell is not recognized, it is replaced with "empty cell". In case with "New highscore" it, apparently creates an impossible field that crashes the solver. Setting STOP_AT_UNKNOWN_CELL to True will make it just through an exception and stop in these situations.

(I am a little concerned that yu had unread cells in some of the games, although it did't stop the bot from winning... weird)
